### ISSUE TITLE
Unavailable Fuel Range and Fuel Level 

### ISSUE THREAD

**Issue by pedroRSL** [ad-ha/mg-saic-ha#24] opened 2024-11-10 23:33 UTC
Fuel Range and Fuel Level are unavailable from this version. It worked without any problems on the previous one. (MG HS2)

**Comment by ad-ha** [comment] 2024-11-10 23:49
Hi @pedroRSL

It might be caused by the check on the vehicle type. It you installed an early version, where this data was nit stored during configuration and was determined automatically based on the data from the API, those sensors may not setup.

Try to remove the integration and re-add it. It shall solve the issue. 

Let me know if this worked.

**Comment by pedroRSL** [comment] 2024-11-11 01:28
I removed and added the integration again. This time I don't have these parameters even on the entity list. I have an ICE version of the car and the day before yesterday I saw how much fuel there is in percentage and what the range is. If I'm not mistaken, the fuel level had a battery icon but it showed the percentage of fuel in the tank.

**Comment by ad-ha** [comment] 2024-11-11 07:24
Thanks for the feedback. Let me check what might have caused it and will let you know.

As I don't have an ICE to try, it gets tricky to know what gets affected, but for sure we can work out on a fix.

I will try to get in fixed today.

Cheers

**Comment by ad-ha** [comment] 2024-11-11 08:50
Hi @pedroRSL 

This shall be fixed on 0.4.5 (https://github.com/ad-ha/mg-saic-ha/releases/tag/0.4.5)

Try to update and restart HA, once you do so you shall see those sensors back. Including the appropriate icons for ICE :)

Let me know if it all works now.

Cheers

**Comment by pedroRSL** [comment] 2024-11-11 11:32
Everything is back to normal. Thanks for the quick fix. Great integration and great work 😁

**Comment by ad-ha** [comment] 2024-11-11 12:30
Thanks for the feedback. And sorry for the inconvenience. Before I forgot the ICE on the conditions for sensors.

Glad it's working again.

**Closed** 2024-11-11 12:30 UTC
